version: "3"
services:
  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: "docker-redis"
    volumes:
      - ./spring-docker-data/redis:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379